quote:([]time:`timestamp$(); sym:`g#`symbol$(); bid:`float$(); ask:`float$(); bsize:`long$(); asize:`long$(); mode:`char$(); ex:`char$(); src:`symbol$())
trade:([]time:`timestamp$(); sym:`g#`symbol$(); price:`float$(); size:`int$(); stop:`boolean$(); cond:`char$(); ex:`char$();side:`symbol$())
quote_iex:([]time:`timestamp$(); sym:`g#`symbol$(); bid:`float$(); ask:`float$(); bsize:`long$(); asize:`long$(); mode:`char$(); ex:`char$(); srctime:`timestamp$())
trade_iex:([]time:`timestamp$(); sym:`g#`symbol$(); price:`float$(); size:`int$(); stop:`boolean$(); cond:`char$(); ex:`char$(); srctime:`timestamp$())
timing0:([]time:`timestamp$(); sym:`symbol$(); feedtime:`timestamp$())
timing1:([]time:`timestamp$(); sym:`symbol$(); feedtime:`timestamp$())
timingdata0:([]time:`timestamp$(); sym:`g#`symbol$(); price:`float$(); size:`int$(); ind:`boolean$(); str1:(); str2:(); side:`symbol$(); feedtime:`timestamp$())
timingdata1:([]time:`timestamp$(); sym:`g#`symbol$(); price:`float$(); size:`int$(); ind:`boolean$(); str1:(); str2:(); side:`symbol$(); feedtime:`timestamp$())
